
obj-y += image_g2d.o
obj-y += soft_g2d.o

obj-y += fill_image_bgra8888.o
obj-y += fill_image_rgba8888.o
obj-y += fill_image_rgb888.o

# dst src
obj-y += blend_image_bgra8888_bgra8888.o
obj-y += blend_image_bgra8888_rgba8888.o
obj-y += blend_image_bgra8888_rgb888.o

obj-y += blend_image_rgba8888_bgra8888.o
obj-y += blend_image_rgba8888_rgba8888.o

obj-y += blend_image_bgr888_bgra8888.o
obj-y += blend_image_bgr888_rgba8888.o

obj-y += blend_image_rgb888_bgra8888.o
obj-y += blend_image_rgb888_rgba8888.o

obj-y += rotate_image_bgra8888.o
obj-y += rotate_image_rgba8888.o
